### ISSUE TITLE
provide routemaster via hub.docker.com

### ISSUE THREAD

**Issue by jeffreylo** [deliveroo/routemaster#118]
I think it’d be really great for the community to provide a self-contained (hehe) image.

**Comment by bencord0** [comment]
This seems reasonable. We can even provide a non-ci docker-compose.yml too.

Would you expect a public docker container of routemaster to run under `hopper-runner`?

Are the use cases limited to local/dev instances of routemaster?

Do we expect people to use a Deliveroo managed Docker Image on a non-Deliveroo managed cluster?

**Comment by jeffreylo** [comment]
> Would you expect a public docker container of routemaster to run under hopper-runner?

I wouldn’t. `hopper-runner` seems chiefly associated with providing encrypted variables to the environment, but that shouldn’t be a dependency to run `routemaster`.

> Are the use cases limited to local/dev instances of routemaster?

The issue _was_ filed with that in mind, but I don’t think it’s limited to local/dev instances.

> Do we expect people to use a Deliveroo managed Docker Image on a non-Deliveroo managed cluster?

Kinda related to your `hopper-runner` question. I don’t expect people to use this Docker image outside of Deliveroo considering [the project only has 6 forks](https://github.com/deliveroo/routemaster/network) and a single external contributor.
